/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type AiFunction = {
	_id: string;
	_type: 'aiFunction';
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	title?: string;
	slug?: Slug;
	icon?: string;
	summary?: string;
};

export type Footer = {
	_id: string;
	_type: 'footer';
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	statement?: string;
	columns?: Array<{
		heading?: string;
		links?: Array<
			{
				_key: string;
			} & Link
		>;
		_type: 'megaColumn';
		_key: string;
	}>;
	legal?: Array<
		{
			_key: string;
		} & Link
	>;
	newsletterText?: string;
};

export type ProductReference = {
	_ref: string;
	_type: 'reference';
	_weak?: boolean;
	[internalGroqTypeReferenceTo]?: 'product';
};

export type Navigation = {
	_id: string;
	_type: 'navigation';
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	items?: Array<{
		link?: Link;
		mega?: 'none' | 'catalogue' | 'columns';
		columns?: Array<{
			heading?: string;
			links?: Array<
				{
					_key: string;
				} & Link
			>;
			_type: 'megaColumn';
			_key: string;
		}>;
		featured?: ProductReference;
		_type: 'navItem';
		_key: string;
	}>;
	utility?: Array<
		{
			_key: string;
		} & Link
	>;
	cta?: Link;
};

export type HomePageReference = {
	_ref: string;
	_type: 'reference';
	_weak?: boolean;
	[internalGroqTypeReferenceTo]?: 'homePage';
};

export type ProductCategoryReference = {
	_ref: string;
	_type: 'reference';
	_weak?: boolean;
	[internalGroqTypeReferenceTo]?: 'productCategory';
};

export type ProductSubcategoryReference = {
	_ref: string;
	_type: 'reference';
	_weak?: boolean;
	[internalGroqTypeReferenceTo]?: 'productSubcategory';
};

export type ProductSeriesReference = {
	_ref: string;
	_type: 'reference';
	_weak?: boolean;
	[internalGroqTypeReferenceTo]?: 'productSeries';
};

export type TechnologyReference = {
	_ref: string;
	_type: 'reference';
	_weak?: boolean;
	[internalGroqTypeReferenceTo]?: 'technology';
};

export type SolutionReference = {
	_ref: string;
	_type: 'reference';
	_weak?: boolean;
	[internalGroqTypeReferenceTo]?: 'solution';
};

export type IndustryReference = {
	_ref: string;
	_type: 'reference';
	_weak?: boolean;
	[internalGroqTypeReferenceTo]?: 'industry';
};

export type ComingSoonPageReference = {
	_ref: string;
	_type: 'reference';
	_weak?: boolean;
	[internalGroqTypeReferenceTo]?: 'comingSoonPage';
};

export type Link = {
	_type: 'link';
	label?: string;
	kind?: 'internal' | 'external';
	reference?:
		| HomePageReference
		| ProductCategoryReference
		| ProductSubcategoryReference
		| ProductSeriesReference
		| ProductReference
		| TechnologyReference
		| SolutionReference
		| IndustryReference
		| ComingSoonPageReference;
	href?: string;
	section?:
		| 'solutions'
		| 'technologies'
		| 'partners'
		| 'support'
		| 'newsroom'
		| 'about'
		| 'contact'
		| 'downloads';
};

export type SanityImageAssetReference = {
	_ref: string;
	_type: 'reference';
	_weak?: boolean;
	[internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
};

export type SiteSettings = {
	_id: string;
	_type: 'siteSettings';
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	companyName?: string;
	brandName?: string;
	logoDark?: {
		asset?: SanityImageAssetReference;
		media?: unknown;
		hotspot?: SanityImageHotspot;
		crop?: SanityImageCrop;
		_type: 'image';
	};
	logoLight?: {
		asset?: SanityImageAssetReference;
		media?: unknown;
		hotspot?: SanityImageHotspot;
		crop?: SanityImageCrop;
		_type: 'image';
	};
	monogram?: {
		asset?: SanityImageAssetReference;
		media?: unknown;
		hotspot?: SanityImageHotspot;
		crop?: SanityImageCrop;
		_type: 'image';
	};
	seo?: Seo;
	siteUrl?: string;
	email?: string;
	phone?: string;
	address?: string;
	social?: Array<{
		platform?: 'linkedin' | 'youtube' | 'x' | 'instagram' | 'facebook';
		url?: string;
		_type: 'socialLink';
		_key: string;
	}>;
	motion?: {
		smoothScroll?: boolean;
		pageTransitions?: boolean;
		grain?: boolean;
	};
};

export type Seo = {
	_type: 'seo';
	title?: string;
	description?: string;
	image?: AltImage;
	noIndex?: boolean;
};

export type SanityImageCrop = {
	_type: 'sanity.imageCrop';
	top?: number;
	bottom?: number;
	left?: number;
	right?: number;
};

export type SanityImageHotspot = {
	_type: 'sanity.imageHotspot';
	x?: number;
	y?: number;
	height?: number;
	width?: number;
};

export type RichTextSection = {
	_type: 'richTextSection';
	title?: string;
	body?: Array<{
		children?: Array<{
			marks?: Array<string>;
			text?: string;
			_type: 'span';
			_key: string;
		}>;
		style?: 'normal' | 'h3' | 'blockquote';
		listItem?: 'bullet' | 'number';
		markDefs?: Array<
			{
				_key: string;
			} & Link
		>;
		level?: number;
		_type: 'block';
		_key: string;
	}>;
	anchor?: string;
};

export type LogoCloud = {
	_type: 'logoCloud';
	title?: string;
	items?: Array<{
		name?: string;
		detail?: string;
		logo?: AltImage;
		_type: 'trustItem';
		_key: string;
	}>;
	anchor?: string;
};

export type CtaSearch = {
	_type: 'ctaSearch';
	title?: string;
	lead?: string;
	placeholder?: string;
	suggestions?: Array<string>;
	anchor?: string;
};

export type FeaturedProducts = {
	_type: 'featuredProducts';
	title?: string;
	lead?: string;
	products?: Array<
		{
			_key: string;
		} & ProductReference
	>;
	anchor?: string;
};

export type IndustriesMosaic = {
	_type: 'industriesMosaic';
	title?: string;
	lead?: string;
	industries?: Array<
		{
			_key: string;
		} & IndustryReference
	>;
	anchor?: string;
};

export type StatsBand = {
	_type: 'statsBand';
	title?: string;
	lead?: string;
	stats?: Array<{
		value?: number;
		suffix?: string;
		label?: string;
		trend?: Array<number>;
		_type: 'stat';
		_key: string;
	}>;
	anchor?: string;
};

export type ExplodedView = {
	_type: 'explodedView';
	title?: string;
	lead?: string;
	frames?: Array<{
		asset?: SanityImageAssetReference;
		media?: unknown;
		hotspot?: SanityImageHotspot;
		crop?: SanityImageCrop;
		_type: 'image';
		_key: string;
	}>;
	framesBaseUrl?: string;
	frameCount?: number;
	poster?: AltImage;
	callouts?: Array<{
		frame?: number;
		title?: string;
		body?: string;
		x?: number;
		y?: number;
		_type: 'callout';
		_key: string;
	}>;
	anchor?: string;
};

export type CategoryRail = {
	_type: 'categoryRail';
	title?: string;
	lead?: string;
	categories?: Array<
		{
			_key: string;
		} & ProductCategoryReference
	>;
	anchor?: string;
};

export type DuskToNight = {
	_type: 'duskToNight';
	title?: string;
	lead?: string;
	technology?: TechnologyReference;
	dayImage?: AltImage;
	conventionalImage?: AltImage;
	enhancedImage?: AltImage;
	conventionalLabel?: string;
	enhancedLabel?: string;
	anchor?: string;
};

export type SanityFileAssetReference = {
	_ref: string;
	_type: 'reference';
	_weak?: boolean;
	[internalGroqTypeReferenceTo]?: 'sanity.fileAsset';
};

export type HeroAperture = {
	_type: 'heroAperture';
	headline?: string;
	lead?: string;
	primaryCta?: Link;
	secondaryCta?: Link;
	image?: AltImage;
	video?: {
		asset?: SanityFileAssetReference;
		media?: unknown;
		_type: 'file';
	};
	detections?: Array<{
		label?: 'PERSON' | 'VEHICLE' | 'BICYCLE' | 'PLATE' | 'FACE';
		confidence?: number;
		x?: number;
		y?: number;
		w?: number;
		h?: number;
		_type: 'detection';
		_key: string;
	}>;
	show3d?: boolean;
	anchor?: string;
};

export type Dori = {
	_type: 'dori';
	detect?: number;
	observe?: number;
	recognize?: number;
	identify?: number;
};

export type Variant = {
	_type: 'variant';
	suffix?: string;
	lensMm?: number;
	status?: 'new' | 'active' | 'discontinued';
};

export type Download = {
	_type: 'download';
	title?: string;
	kind?: 'datasheet' | 'manual' | 'firmware' | 'cad' | 'certificate';
	file?: {
		asset?: SanityFileAssetReference;
		media?: unknown;
		_type: 'file';
	};
	externalUrl?: string;
	version?: string;
	date?: string;
	sizeBytes?: number;
	language?: string;
};

export type SpecGroup = {
	_type: 'specGroup';
	group?:
		| 'Camera'
		| 'Lens'
		| 'Pixel density (DORI)'
		| 'Illuminator'
		| 'Video'
		| 'Audio'
		| 'Network'
		| 'Image'
		| 'Interface'
		| 'Event'
		| 'Deep-learning function'
		| 'General'
		| 'Approval';
	rows?: Array<{
		key?: string;
		value?: string;
		_type: 'specRow';
		_key: string;
	}>;
};

export type ComingSoonPage = {
	_id: string;
	_type: 'comingSoonPage';
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	section?:
		| 'solutions'
		| 'technologies'
		| 'partners'
		| 'support'
		| 'newsroom'
		| 'about'
		| 'contact'
		| 'downloads';
	title?: string;
	lead?: string;
	eta?: string;
	links?: Array<
		{
			_key: string;
		} & Link
	>;
};

export type Industry = {
	_id: string;
	_type: 'industry';
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	title?: string;
	slug?: Slug;
	summary?: string;
	image?: AltImage;
};

export type AltImage = {
	_type: 'altImage';
	asset?: SanityImageAssetReference;
	media?: unknown;
	hotspot?: SanityImageHotspot;
	crop?: SanityImageCrop;
	alt?: string;
	decorative?: boolean;
	credit?: string;
};

export type Solution = {
	_id: string;
	_type: 'solution';
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	title?: string;
	slug?: Slug;
	axis?: 'industry' | 'function' | 'scenario';
	industries?: Array<
		{
			_key: string;
		} & IndustryReference
	>;
	summary?: string;
	image?: AltImage;
};

export type Technology = {
	_id: string;
	_type: 'technology';
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	title?: string;
	slug?: Slug;
	icon?: string;
	summary?: string;
	proofPoint?: string;
	image?: AltImage;
};

export type FormFactorReference = {
	_ref: string;
	_type: 'reference';
	_weak?: boolean;
	[internalGroqTypeReferenceTo]?: 'formFactor';
};

export type AiFunctionReference = {
	_ref: string;
	_type: 'reference';
	_weak?: boolean;
	[internalGroqTypeReferenceTo]?: 'aiFunction';
};

export type Product = {
	_id: string;
	_type: 'product';
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	modelNumber?: string;
	name?: string;
	slug?: Slug;
	status?: 'new' | 'active' | 'discontinued';
	releaseDate?: string;
	category?: ProductCategoryReference;
	subcategory?: ProductSubcategoryReference;
	series?: ProductSeriesReference;
	shortDescription?: string;
	highlights?: Array<string>;
	cardSpecs?: Array<{
		label?: string;
		value?: string;
		unit?: string;
		_type: 'cardSpec';
		_key: string;
	}>;
	heroImage?: AltImage;
	gallery?: Array<
		{
			_key: string;
		} & AltImage
	>;
	spinFrames?: Array<{
		asset?: SanityImageAssetReference;
		media?: unknown;
		hotspot?: SanityImageHotspot;
		crop?: SanityImageCrop;
		_type: 'image';
		_key: string;
	}>;
	resolutionMp?: number;
	sensor?: string;
	lensMm?: number;
	lensMmMax?: number;
	lensType?: 'fixed' | 'manual-varifocal' | 'motorized-varifocal' | 'multi-lens';
	opticalZoom?: number;
	lightType?: 'ir' | 'white' | 'hybrid' | 'none';
	irDistanceM?: number;
	ipRating?: 'IP54' | 'IP66' | 'IP67' | 'IP68';
	ikRating?: 'IK08' | 'IK10';
	poe?: boolean;
	audio?: Array<string>;
	deterrence?: Array<string>;
	power?: Array<string>;
	channels?: number;
	storage?: string;
	operatingTemp?: string;
	dori?: Dori;
	fullSpecs?: Array<
		{
			_key: string;
		} & SpecGroup
	>;
	formFactor?: FormFactorReference;
	technologies?: Array<
		{
			_key: string;
		} & TechnologyReference
	>;
	aiFunctions?: Array<
		{
			_key: string;
		} & AiFunctionReference
	>;
	variants?: Array<
		{
			_key: string;
		} & Variant
	>;
	relatedProducts?: Array<
		{
			_key: string;
		} & ProductReference
	>;
	comparedWith?: Array<
		{
			_key: string;
		} & ProductReference
	>;
	relatedSolutions?: Array<
		{
			_key: string;
		} & SolutionReference
	>;
	compatibleWith?: Array<
		{
			_key: string;
		} & ProductReference
	>;
	bundleItems?: Array<{
		product?: ProductReference;
		quantity?: number;
		_type: 'bundleItem';
		_key: string;
	}>;
	downloads?: Array<
		{
			_key: string;
		} & Download
	>;
	seo?: Seo;
};

export type FormFactor = {
	_id: string;
	_type: 'formFactor';
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	title?: string;
	slug?: Slug;
	icon?: string;
	summary?: string;
};

export type Slug = {
	_type: 'slug';
	current?: string;
	source?: string;
};

export type ProductSeries = {
	_id: string;
	_type: 'productSeries';
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	title?: string;
	slug?: Slug;
	tier?: 'value' | 'pro' | 'ultra' | 'ai' | 'panoramic' | 'special';
	subcategories?: Array<
		{
			_key: string;
		} & ProductSubcategoryReference
	>;
	tagline?: string;
};

export type ProductSubcategory = {
	_id: string;
	_type: 'productSubcategory';
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	orderRank?: string;
	title?: string;
	slug?: Slug;
	category?: ProductCategoryReference;
	description?: string;
	heroImage?: AltImage;
	filterConfig?: Array<{
		attribute?:
			| 'series'
			| 'formFactor'
			| 'resolutionMp'
			| 'lensType'
			| 'lightType'
			| 'aiFunctions'
			| 'ipRating'
			| 'ikRating'
			| 'poe'
			| 'audio'
			| 'deterrence'
			| 'power'
			| 'channels';
		ui?: 'checkbox' | 'range' | 'toggle';
		label?: string;
		collapsed?: boolean;
		_type: 'filter';
		_key: string;
	}>;
	seo?: Seo;
};

export type ProductCategory = {
	_id: string;
	_type: 'productCategory';
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	orderRank?: string;
	title?: string;
	slug?: Slug;
	icon?:
		| 'camera-network'
		| 'camera-ptz'
		| 'recorder'
		| 'thermal'
		| 'access'
		| 'intercom'
		| 'alarm'
		| 'display'
		| 'network-switch'
		| 'traffic'
		| 'software';
	tagline?: string;
	description?: string;
	heroImage?: AltImage;
	seo?: Seo;
};

export type HomePage = {
	_id: string;
	_type: 'homePage';
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	title?: string;
	sections?: Array<
		| ({
				_key: string;
		  } & HeroAperture)
		| ({
				_key: string;
		  } & DuskToNight)
		| ({
				_key: string;
		  } & CategoryRail)
		| ({
				_key: string;
		  } & ExplodedView)
		| ({
				_key: string;
		  } & StatsBand)
		| ({
				_key: string;
		  } & IndustriesMosaic)
		| ({
				_key: string;
		  } & FeaturedProducts)
		| ({
				_key: string;
		  } & CtaSearch)
		| ({
				_key: string;
		  } & LogoCloud)
		| ({
				_key: string;
		  } & RichTextSection)
	>;
	seo?: Seo;
};

export type SanityImagePaletteSwatch = {
	_type: 'sanity.imagePaletteSwatch';
	background?: string;
	foreground?: string;
	population?: number;
	title?: string;
};

export type SanityImagePalette = {
	_type: 'sanity.imagePalette';
	darkMuted?: SanityImagePaletteSwatch;
	lightVibrant?: SanityImagePaletteSwatch;
	darkVibrant?: SanityImagePaletteSwatch;
	vibrant?: SanityImagePaletteSwatch;
	dominant?: SanityImagePaletteSwatch;
	lightMuted?: SanityImagePaletteSwatch;
	muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
	_type: 'sanity.imageDimensions';
	height?: number;
	width?: number;
	aspectRatio?: number;
};

export type SanityImageMetadata = {
	_type: 'sanity.imageMetadata';
	location?: Geopoint;
	dimensions?: SanityImageDimensions;
	palette?: SanityImagePalette;
	lqip?: string;
	blurHash?: string;
	thumbHash?: string;
	hasAlpha?: boolean;
	isOpaque?: boolean;
};

export type SanityFileAsset = {
	_id: string;
	_type: 'sanity.fileAsset';
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	originalFilename?: string;
	label?: string;
	title?: string;
	description?: string;
	altText?: string;
	sha1hash?: string;
	extension?: string;
	mimeType?: string;
	size?: number;
	assetId?: string;
	uploadId?: string;
	path?: string;
	url?: string;
	source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
	_type: 'sanity.assetSourceData';
	name?: string;
	id?: string;
	url?: string;
};

export type SanityImageAsset = {
	_id: string;
	_type: 'sanity.imageAsset';
	_createdAt: string;
	_updatedAt: string;
	_rev: string;
	originalFilename?: string;
	label?: string;
	title?: string;
	description?: string;
	altText?: string;
	sha1hash?: string;
	extension?: string;
	mimeType?: string;
	size?: number;
	assetId?: string;
	uploadId?: string;
	path?: string;
	url?: string;
	metadata?: SanityImageMetadata;
	source?: SanityAssetSourceData;
};

export type Geopoint = {
	_type: 'geopoint';
	lat?: number;
	lng?: number;
	alt?: number;
};

export type AllSanitySchemaTypes =
	| AiFunction
	| Footer
	| ProductReference
	| Navigation
	| HomePageReference
	| ProductCategoryReference
	| ProductSubcategoryReference
	| ProductSeriesReference
	| TechnologyReference
	| SolutionReference
	| IndustryReference
	| ComingSoonPageReference
	| Link
	| SanityImageAssetReference
	| SiteSettings
	| Seo
	| SanityImageCrop
	| SanityImageHotspot
	| RichTextSection
	| LogoCloud
	| CtaSearch
	| FeaturedProducts
	| IndustriesMosaic
	| StatsBand
	| ExplodedView
	| CategoryRail
	| DuskToNight
	| SanityFileAssetReference
	| HeroAperture
	| Dori
	| Variant
	| Download
	| SpecGroup
	| ComingSoonPage
	| Industry
	| AltImage
	| Solution
	| Technology
	| FormFactorReference
	| AiFunctionReference
	| Product
	| FormFactor
	| Slug
	| ProductSeries
	| ProductSubcategory
	| ProductCategory
	| HomePage
	| SanityImagePaletteSwatch
	| SanityImagePalette
	| SanityImageDimensions
	| SanityImageMetadata
	| SanityFileAsset
	| SanityAssetSourceData
	| SanityImageAsset
	| Geopoint;
